### ISSUE TITLE
AWS setting & 이미지url 송수신

### ISSUE THREAD

**Issue by gilyeon00** [2022-SeongNam-Team-C/Ladder-Backend#8]
- [x] s3 bucket 생성
- [x] IAM 설정
- [x] AWS setting
- [x] 이미지 url 송신
- [x] 이미지 url 수신

**Comment by yu-heejin** [comment]
- [ ] 사용자 이미지 히스토리 부분 구현

**Comment by gilyeon00** [comment]
- [ ] docker live reloading
- [ ] 한국 시간으로 설정

**Comment by gilyeon00** [comment]
- [ ] DB columns 수정
- [ ] Debug mode on (live reloading)
